.TH AD_PACKAGE 1 "2026-09-10" "ad 2.0" "ad scripts"
.SH NAME
ad_package \- package the project for distribution
.SH SYNOPSIS
.B ad_package
.RI [ version ]
.SH DESCRIPTION
.B ad_package
builds the C binaries (compute, animator-c, postprocess, pace) from
source, then archives them together with the Perl pipeline, the
launcher scripts (ad_vim, ad_vim.pl, ad_tmux, ad_compare), the Vim
plugin (plugin/, autoload/, completion/, man/, DiffVim/), the
tests/examples/, the scripts/, README, CHANGELOG and LICENSE into a
single distributable
.IR .tar.gz .
.PP
The resulting tarball is written to
.IR /tmp/ad-<version>.tar.gz .
.SH OPTIONS
.TP
.BR \-h , " \-\-help"
Show detailed help and exit.
.SH ARGUMENTS
.TP
.I version
Version string to embed in the tarball filename. Defaults to
.I 2.0
if not supplied.
.SH EXAMPLES
.TP
.B ad_package
Build the 2.0 release tarball at
.IR /tmp/ad-2.0.tar.gz .
.TP
.B ad_package 2.3.1
Build the 2.3.1 release tarball at
.IR /tmp/ad-2.3.1.tar.gz .
.SH "SEE ALSO"
.BR ad_vim (1),
.BR ad_pipeline (1)
