// diffvim-pace — Transform ordered ops into a timed op stream.
// Go implementation — produces identical output to the Perl version.
//
// Usage: diffvim-pace [--delete-pacing MODE] [--delete-speed MODE]
//                     [--delete-threshold N] [--insert-pacing MODE]
//                     [--insert-speed MODE] [--pacing MODE] [--snapshot FILE]
//
// Build: go build -o diffvim-pace pace.go

package main

import (
        "bufio"
        "fmt"
        "os"
        "strconv"
        "strings"
)

type Op struct {
        Type string
        Code int
}

type Hunk struct {
        Target, Del, Ins, EndIns, EndDel int
        Ops                              []Op
}

var deletePacing = "word"
var deleteSpeed = "normal"
var deleteThreshold = 3
var insertPacing = "char"
var insertSpeed = "normal"
var pacing = "uniform"
var snapshotFile = ""

// Default timing values
var typeDelay = 50
var deleteDelay = 40
var hunkPause = 250
var rapidEolDelay = 80
var awdStartChars = 3
var awdStartMs = 80
var awdMinMs = 15
var awdAccel = 0.85
var awdWordPause = 100
var wordPause = 150
var moveMinMs = 250
var moveMaxMs = 1600
var moveMsPerUnit = 6

func parseArgs(args []string) {
        for i := 0; i < len(args); i++ {
                switch args[i] {
                case "--delete-pacing":
                        if i+1 < len(args) { i++; deletePacing = args[i] }
                case "--delete-speed":
                        if i+1 < len(args) { i++; deleteSpeed = args[i] }
                case "--delete-threshold":
                        if i+1 < len(args) { i++; deleteThreshold, _ = strconv.Atoi(args[i]) }
                case "--insert-pacing":
                        if i+1 < len(args) { i++; insertPacing = args[i] }
                case "--insert-speed":
                        if i+1 < len(args) { i++; insertSpeed = args[i] }
                case "--pacing":
                        if i+1 < len(args) { i++; pacing = args[i] }
                case "--snapshot":
                        if i+1 < len(args) { i++; snapshotFile = args[i] }
                case "--help", "-h":
                        fmt.Fprintln(os.Stderr, "Usage: diffvim-pace [--delete-pacing MODE] [--delete-speed MODE] [--delete-threshold N] [--insert-pacing MODE] [--insert-speed MODE] [--pacing MODE] [--snapshot FILE]")
                        os.Exit(0)
                }
        }
}

func applySpeeds() {
        if deleteSpeed == "fast" {
                deleteDelay /= 2
                awdStartMs /= 2
        } else if deleteSpeed == "instant" {
                deleteDelay = 1
                awdStartMs = 1
                awdMinMs = 1
        }
        if insertSpeed == "fast" {
                typeDelay /= 2
                wordPause /= 2
        } else if insertSpeed == "slow" {
                typeDelay *= 2
                wordPause *= 2
        }
}

func main() {
        parseArgs(os.Args[1:])
        applySpeeds()

        scanner := bufio.NewScanner(os.Stdin)
        scanner.Buffer(make([]byte, 1024*1024), 1024*1024)

        var hunks []Hunk
        var currentHunk *Hunk

        for scanner.Scan() {
                line := scanner.Text()
                if strings.HasPrefix(line, "#") {
                        continue
                }
                if strings.HasPrefix(line, "HUNK ") {
                        parts := strings.Fields(line)
                        if len(parts) >= 6 {
                                target, _ := strconv.Atoi(parts[1])
                                del, _ := strconv.Atoi(parts[2])
                                ins, _ := strconv.Atoi(parts[3])
                                endIns, _ := strconv.Atoi(parts[4])
                                endDel, _ := strconv.Atoi(parts[5])
                                hunks = append(hunks, Hunk{Target: target, Del: del, Ins: ins, EndIns: endIns, EndDel: endDel})
                                currentHunk = &hunks[len(hunks)-1]
                        }
                        continue
                }
                parts := strings.Fields(line)
                if len(parts) >= 2 && (parts[0] == "keep" || parts[0] == "delete" || parts[0] == "insert") {
                        code, _ := strconv.Atoi(parts[1])
                        if currentHunk != nil {
                                currentHunk.Ops = append(currentHunk.Ops, Op{Type: parts[0], Code: code})
                        }
                }
        }

        w := bufio.NewWriter(os.Stdout)
        defer w.Flush()

        fmt.Fprintf(w, "# timed op stream v1\n")
        fmt.Fprintf(w, "# generated by: diffvim-pace --delete-pacing %s --delete-speed %s --insert-pacing %s --pacing %s\n", deletePacing, deleteSpeed, insertPacing, pacing)
        fmt.Fprintf(w, "# delete_threshold %d\n", deleteThreshold)

        currentLine := 1

        for hunkIdx, hunk := range hunks {
                target := hunk.Target
                ops := hunk.Ops

                // Compute glide
                dl := target - currentLine
                if dl < 0 {
                        dl = -dl
                }
                distance := dl * 80
                glideMs := moveMinMs
                if distance*moveMsPerUnit > moveMinMs {
                        glideMs = distance * moveMsPerUnit
                        if glideMs > moveMaxMs {
                                glideMs = moveMaxMs
                        }
                }

                fmt.Fprintf(w, "hunk_start %d %d %d\n", target, hunk.Del, hunk.Ins)
                fmt.Fprintf(w, "glide %d:1\n", target)
                fmt.Fprintf(w, "delay %d\n", glideMs)

                currentLine = target
                currentCol := 1

                i := 0
                for i < len(ops) {
                        op := ops[i]
                        if op.Type == "keep" {
                                if op.Code == 10 {
                                        currentLine++
                                        currentCol = 1
                                } else {
                                        currentCol++
                                }
                                fmt.Fprintf(w, "op keep %d\n", op.Code)
                                fmt.Fprintf(w, "delay 1\n")
                                i++
                        } else if op.Type == "delete" {
                                if op.Code == 10 {
                                        fmt.Fprintf(w, "newline_delete\n")
                                        fmt.Fprintf(w, "delay %d\n", deleteDelay)
                                        currentLine++
                                        currentCol = 1
                                        i++
                                } else {
                                        i, currentCol = processDelete(w, ops, i, deletePacing, currentCol)
                                }
                        } else if op.Type == "insert" {
                                if op.Code == 10 {
                                        fmt.Fprintf(w, "newline_insert\n")
                                        fmt.Fprintf(w, "delay %d\n", typeDelay)
                                        currentLine++
                                        currentCol = 1
                                        i++
                                } else if insertPacing == "word" {
                                        // Batch short words
                                        wordLen := 0
                                        for j := i; j < len(ops) && ops[j].Type == "insert" && ops[j].Code != 10 && ops[j].Code != 32; j++ {
                                                wordLen++
                                        }
                                        if wordLen >= 2 && wordLen <= 8 {
                                                codes := make([]string, wordLen)
                                                for k := 0; k < wordLen; k++ {
                                                        codes[k] = strconv.Itoa(ops[i+k].Code)
                                                }
                                                fmt.Fprintf(w, "batch_insert %s\n", strings.Join(codes, " "))
                                                fmt.Fprintf(w, "delay %d\n", wordPause)
                                                currentCol += wordLen
                                                i += wordLen
                                        } else {
                                                fmt.Fprintf(w, "op insert %d\n", op.Code)
                                                fmt.Fprintf(w, "delay %d\n", typeDelay)
                                                currentCol++
                                                i++
                                        }
                                } else {
                                        fmt.Fprintf(w, "op insert %d\n", op.Code)
                                        fmt.Fprintf(w, "delay %d\n", typeDelay)
                                        currentCol++
                                        i++
                                }
                        }
                }

                fmt.Fprintf(w, "hunk_end\n")
                if hunkIdx < len(hunks)-1 {
                        fmt.Fprintf(w, "delay %d\n", hunkPause)
                }
        }

        if snapshotFile != "" {
                fmt.Fprintf(w, "snapshot %s\n", snapshotFile)
        }
        fmt.Fprintf(w, "done\n")
}

func processDelete(w *bufio.Writer, ops []Op, start int, pacingMode string, currentCol int) (int, int) {
        // Count consecutive non-newline deletes
        count := 0
        for j := start; j < len(ops) && ops[j].Type == "delete" && ops[j].Code != 10; j++ {
                count++
        }
        if count == 0 {
                fmt.Fprintf(w, "op delete %d\n", ops[start].Code)
                fmt.Fprintf(w, "delay %d\n", deleteDelay)
                return start + 1, currentCol
        }

        switch pacingMode {
        case "char":
                fmt.Fprintf(w, "op delete %d\n", ops[start].Code)
                fmt.Fprintf(w, "delay %d\n", deleteDelay)
                return start + 1, currentCol - 1

        case "instant":
                fmt.Fprintf(w, "batch_delete %d\n", count)
                fmt.Fprintf(w, "delay %d\n", rapidEolDelay)
                return start + count, currentCol - count

        case "rapid-eol":
                atEol := start+count >= len(ops) || ops[start+count].Code == 10 ||
                        (ops[start+count].Type == "keep" && ops[start+count].Code == 10)
                if atEol && count >= deleteThreshold {
                        fmt.Fprintf(w, "batch_delete %d\n", count)
                        fmt.Fprintf(w, "delay %d\n", rapidEolDelay)
                        return start + count, currentCol - count
                }
                fmt.Fprintf(w, "op delete %d\n", ops[start].Code)
                fmt.Fprintf(w, "delay %d\n", deleteDelay)
                return start + 1, currentCol - 1

        case "word":
                return processAWD(w, ops, start, count)

        default:
                fmt.Fprintf(w, "op delete %d\n", ops[start].Code)
                fmt.Fprintf(w, "delay %d\n", deleteDelay)
                return start + 1, currentCol - 1
        }
}

func processAWD(w *bufio.Writer, ops []Op, start, count int) (int, int) {
        end := start + count
        i := start
        advance := 0

        // Phase 1: Skip spaces instantly
        for i < end && (ops[i].Code == 32 || ops[i].Code == 9) {
                i++
        }
        if i > start {
                fmt.Fprintf(w, "batch_delete %d\n", i-start)
                fmt.Fprintf(w, "delay %d\n", awdMinMs)
                advance += i - start
        }

        remaining := end - i
        if remaining <= awdStartChars {
                if remaining > 0 {
                        fmt.Fprintf(w, "batch_delete %d\n", remaining)
                        fmt.Fprintf(w, "delay %d\n", awdMinMs)
                }
                return start + count, 0
        }

        // Phase 2: Delete start_chars slowly
        for k := i; k < i+awdStartChars; k++ {
                fmt.Fprintf(w, "op delete %d\n", ops[k].Code)
                fmt.Fprintf(w, "delay %d\n", awdStartMs)
        }
        i += awdStartChars

        // Phase 3: Delete words with acceleration
        delay := float64(awdStartMs)
        for i < end {
                wordLen := 0
                for j := i; j < end && ops[j].Code != 32 && ops[j].Code != 9; j++ {
                        wordLen++
                }
                if wordLen > 0 {
                        fmt.Fprintf(w, "batch_delete %d\n", wordLen)
                        delay *= awdAccel
                        if delay < float64(awdMinMs) {
                                delay = float64(awdMinMs)
                        }
                        fmt.Fprintf(w, "delay %d\n", int(delay))
                        i += wordLen
                }
                // Skip spaces
                if i < end && (ops[i].Code == 32 || ops[i].Code == 9) {
                        spaceStart := i
                        for i < end && (ops[i].Code == 32 || ops[i].Code == 9) {
                                i++
                        }
                        fmt.Fprintf(w, "batch_delete %d\n", i-spaceStart)
                        fmt.Fprintf(w, "delay %d\n", awdMinMs)
                }
        }

        return start + count, 0
}
