#!/usr/bin/env perl
# diffvim-pace — Transforms ordered char ops into a timed op stream.
#
# Reads ordered char ops (from diffvim-postprocess) from stdin, analyzes
# the entire op stream, and produces a timed op stream with pre-computed
# delays, batch operations, cursor glide targets, and pacing decisions.
#
# The animator just plays back the timed op stream — it makes NO pacing
# decisions itself.
#
# Usage:
#   diffvim-pace [options] < ordered_ops > timed_ops
#
# Options:
#   --delete-pacing char|rapid-eol|rapid-identical|accel|word|instant
#       (default: word)
#   --delete-speed slow|normal|fast|instant   (default: normal)
#   --delete-threshold N                     (default: 3)
#   --insert-pacing char|word|accel          (default: char)
#   --insert-speed slow|normal|fast          (default: normal)
#   --pacing uniform|adaptive|gaussian|review (default: uniform)
#   --snapshot FILE   Insert a snapshot op at the end
#   --help, -h        Show help
#
# Timed op stream format (output):
#   # timed op stream v1
#   # generated by: diffvim-pace --delete-pacing word ...
#   file_start <oldfile> <newfile>
#   hunk_start <line> <del_count> <ins_count>
#   glide <line>:<col>
#   delay <ms>
#   op <keep|delete|insert> <code>
#   delay <ms>
#   batch_delete <count>
#   delay <ms>
#   batch_insert <codes...>
#   delay <ms>
#   newline_delete
#   delay <ms>
#   snapshot <file>
#   hunk_end
#   done

use strict;
use warnings;
use Getopt::Long qw(GetOptions);

my $delete_pacing = 'word';
my $delete_speed = 'normal';
my $delete_threshold = 3;
my $insert_pacing = 'char';
my $insert_speed = 'normal';
my $pacing = 'uniform';
my $snapshot_file;
my $help = 0;

GetOptions(
    'delete-pacing=s'  => \$delete_pacing,
    'delete-speed=s'    => \$delete_speed,
    'delete-threshold=i' => \$delete_threshold,
    'insert-pacing=s'   => \$insert_pacing,
    'insert-speed=s'    => \$insert_speed,
    'pacing=s'          => \$pacing,
    'snapshot=s'        => \$snapshot_file,
    'help|h'            => \$help,
) or die "Usage: $0 [options]\n  Run '$0 --help' for details.\n";

if ($help) {
    print STDERR <<USAGE;
diffvim-pace — Transform ordered ops into a timed op stream

Usage: diffvim-pace [options] < ordered_ops > timed_ops

Options:
  --delete-pacing char|rapid-eol|rapid-identical|accel|word|instant
                           Deletion strategy (default: word)
  --delete-speed slow|normal|fast|instant
                           Deletion speed (default: normal)
  --delete-threshold N     Min chars for rapid/word modes (default: 3)
  --insert-pacing char|word|accel
                           Insertion strategy (default: char)
  --insert-speed slow|normal|fast
                           Insertion speed (default: normal)
  --pacing uniform|adaptive|gaussian|review
                           Timing mode (default: uniform)
  --snapshot FILE          Insert a snapshot op at the end
  -h, --help               Show this help

Example:
  diffvim-compute-c old.py new.py |
    diffvim-postprocess --op-order optimize |
    diffvim-pace --delete-pacing word --pacing gaussian |
    diffvim-animator old.py
USAGE
    exit 0;
}

# Validate options
my %valid_dp = map { $_ => 1 } qw(char rapid-eol rapid-identical accel word instant);
die "Invalid --delete-pacing '$delete_pacing'\n" unless $valid_dp{$delete_pacing};
my %valid_ds = map { $_ => 1 } qw(slow normal fast instant);
die "Invalid --delete-speed '$delete_speed'\n" unless $valid_ds{$delete_speed};
my %valid_ip = map { $_ => 1 } qw(char word accel);
die "Invalid --insert-pacing '$insert_pacing'\n" unless $valid_ip{$insert_pacing};
my %valid_is = map { $_ => 1 } qw(slow normal fast);
die "Invalid --insert-speed '$insert_speed'\n" unless $valid_is{$insert_speed};
my %valid_p = map { $_ => 1 } qw(uniform adaptive gaussian review);
die "Invalid --pacing '$pacing'\n" unless $valid_p{$pacing};

# Default timing values (ms)
my $type_delay = 50;
my $delete_delay = 40;
my $hunk_pause = 250;
my $rapid_eol_delay = 80;
my $rapid_eol_min = $delete_threshold;
my $awd_start_chars = 3;
my $awd_start_ms = 80;
my $awd_min_ms = 15;
my $awd_accel = 0.85;
my $awd_word_pause = 100;
my $word_pause = 150;
my $move_min_ms = 250;
my $move_max_ms = 1600;
my $move_ms_per_unit = 6;

# Apply speed multipliers
if ($delete_speed eq 'fast') {
    $delete_delay = int($delete_delay / 2);
    $awd_start_ms = int($awd_start_ms / 2);
} elsif ($delete_speed eq 'instant') {
    $delete_delay = 1;
    $awd_start_ms = 1;
    $awd_min_ms = 1;
}
if ($insert_speed eq 'fast') {
    $type_delay = int($type_delay / 2);
    $word_pause = int($word_pause / 2);
} elsif ($insert_speed eq 'slow') {
    $type_delay = int($type_delay * 2);
    $word_pause = int($word_pause * 2);
}

# Read input
my @header;
my @hunks;
my $current_hunk;

while (my $line = <STDIN>) {
    chomp $line;
    if ($line =~ /^#/) {
        push @header, $line;
        next;
    }
    if ($line =~ /^HUNK\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)$/) {
        $current_hunk = {
            target    => $1,
            del_count  => $2,
            ins_count  => $3,
            end_ins    => $4,
            end_del    => $5,
            ops        => [],
        };
        push @hunks, $current_hunk;
        next;
    }
    if ($line =~ /^(keep|delete|insert)\s+(\d+)$/) {
        push @{$current_hunk->{ops}}, [$1, int($2)];
        next;
    }
}

# Generate timed op stream
print "# timed op stream v1\n";
print "# generated by: diffvim-pace --delete-pacing $delete_pacing --delete-speed $delete_speed --insert-pacing $insert_pacing --pacing $pacing\n";
print "# delete_threshold $delete_threshold\n";

# For each hunk, produce timed ops
my $current_line = 1;
my $current_col = 1;

for my $hunk_idx (0 .. $#hunks) {
    my $hunk = $hunks[$hunk_idx];
    my $target = $hunk->{target};
    my $ops = $hunk->{ops};

    # Compute glide from current position to target
    my $dl = abs($target - $current_line);
    my $dc = abs(1 - $current_col);
    my $distance = $dl * 80 + $dc;  # lines weighted 80x
    my $glide_ms = int($move_min_ms);
    if ($distance * $move_ms_per_unit > $move_min_ms) {
        $glide_ms = int($distance * $move_ms_per_unit);
        $glide_ms = $move_max_ms if $glide_ms > $move_max_ms;
    }

    printf "hunk_start %d %d %d\n", $target, $hunk->{del_count}, $hunk->{ins_count};
    printf "glide %d:1\n", $target;
    printf "delay %d\n", $glide_ms;

    $current_line = $target;
    $current_col = 1;

    # Process ops with pacing
    my $i = 0;
    while ($i < @$ops) {
        my $op = $ops->[$i];

        if ($op->[0] eq 'keep') {
            # Keep: advance cursor
            if ($op->[1] == 10) {  # \n
                $current_line++;
                $current_col = 1;
            } else {
                $current_col++;
            }
            printf "op keep %d\n", $op->[1];
            print "delay 1\n";
            $i++;
        } elsif ($op->[0] eq 'delete') {
            # Delete: apply pacing strategy
            if ($op->[1] == 10) {
                # \n delete
                print "newline_delete\n";
                print "delay $delete_delay\n";
                $current_line++;
                $current_col = 1;
                $i++;
            } else {
                # Non-newline delete: apply delete-pacing
                my ($advance, $delay) = process_delete($ops, $i, $delete_pacing,
                    $delete_delay, $rapid_eol_delay, $rapid_eol_min,
                    $awd_start_chars, $awd_start_ms, $awd_min_ms, $awd_accel,
                    $awd_word_pause);
                $i += $advance;
                $current_col -= $advance if $current_col > $advance;
                $current_col = 1 if $current_col < 1;
                print "delay $delay\n" if $delay > 0;
            }
        } elsif ($op->[0] eq 'insert') {
            # Insert: apply insertion pacing
            if ($op->[1] == 10) {
                print "newline_insert\n";
                print "delay $type_delay\n";
                $current_line++;
                $current_col = 1;
                $i++;
            } else {
                if ($insert_pacing eq 'word') {
                    # Batch short words
                    my $word_len = 0;
                    my $j = $i;
                    while ($j < @$ops && $ops->[$j][0] eq 'insert' && $ops->[$j][1] != 10
                           && $ops->[$j][1] != 32) {
                        $word_len++;
                        $j++;
                    }
                    if ($word_len >= 2 && $word_len <= 8) {
                        # Batch the word
                        my @codes;
                        for my $k ($i .. $i + $word_len - 1) {
                            push @codes, $ops->[$k][1];
                        }
                        printf "batch_insert %s\n", join(' ', @codes);
                        print "delay $word_pause\n";
                        $current_col += $word_len;
                        $i += $word_len;
                    } else {
                        printf "op insert %d\n", $op->[1];
                        print "delay $type_delay\n";
                        $current_col++;
                        $i++;
                    }
                } else {
                    printf "op insert %d\n", $op->[1];
                    print "delay $type_delay\n";
                    $current_col++;
                    $i++;
                }
            }
        }
    }

    print "hunk_end\n";
    print "delay $hunk_pause\n" if $hunk_idx < $#hunks;
}

# Snapshot at end if requested
if ($snapshot_file) {
    print "snapshot $snapshot_file\n";
}

print "done\n";

# --- Pacing functions ---

sub process_delete {
    my ($ops, $start, $pacing, $del_delay, $rapid_delay, $rapid_min,
        $awd_start_chars, $awd_start_ms, $awd_min_ms, $awd_accel, $awd_word_pause) = @_;

    # Count consecutive non-newline deletes
    my $count = 0;
    my $j = $start;
    while ($j < @$ops && $ops->[$j][0] eq 'delete' && $ops->[$j][1] != 10) {
        $count++;
        $j++;
    }

    return (1, $del_delay) if $count == 0;

    if ($pacing eq 'char') {
        # One char at a time
        printf "op delete %d\n", $ops->[$start][1];
        return (1, $del_delay);
    }

    if ($pacing eq 'instant') {
        # Delete all at once
        printf "batch_delete %d\n", $count;
        return ($count, $rapid_delay);
    }

    if ($pacing eq 'rapid-eol') {
        # Check if this extends to EOL (next op is keep-\n, delete-\n, or end)
        my $next_op = $j < @$ops ? $ops->[$j] : undef;
        my $at_eol = (!$next_op) || ($next_op->[0] eq 'keep' && $next_op->[1] == 10)
                      || ($next_op->[0] eq 'delete' && $next_op->[1] == 10);
        if ($at_eol && $count >= $rapid_min) {
            printf "batch_delete %d\n", $count;
            return ($count, $rapid_delay);
        }
        printf "op delete %d\n", $ops->[$start][1];
        return (1, $del_delay);
    }

    if ($pacing eq 'rapid-identical') {
        # Check if all chars are identical
        my $first_code = $ops->[$start][1];
        my $all_same = 1;
        for my $k ($start .. $start + $count - 1) {
            if ($ops->[$k][1] != $first_code) {
                $all_same = 0;
                last;
            }
        }
        if ($all_same && $count >= $rapid_min) {
            printf "batch_delete %d\n", $count;
            return ($count, $rapid_delay);
        }
        printf "op delete %d\n", $ops->[$start][1];
        return (1, $del_delay);
    }

    if ($pacing eq 'accel') {
        # Delete in blocks with acceleration
        if ($count >= 2) {
            # Just batch all for now (simplified)
            printf "batch_delete %d\n", $count;
            return ($count, $awd_min_ms);
        }
        printf "op delete %d\n", $ops->[$start][1];
        return (1, $del_delay);
    }

    if ($pacing eq 'word') {
        # AWD: spaces instantly, then 3 chars slow, then words, then rest rapid
        return process_awd($ops, $start, $count, $del_delay, $awd_start_chars,
            $awd_start_ms, $awd_min_ms, $awd_accel, $awd_word_pause);
    }

    # Default
    printf "op delete %d\n", $ops->[$start][1];
    return (1, $del_delay);
}

sub process_awd {
    my ($ops, $start, $count, $del_delay, $start_chars, $start_ms, $min_ms, $accel, $word_pause) = @_;

    my $i = $start;
    my $end = $start + $count;
    my $non_space_count = 0;

    # Phase 1: Skip spaces instantly
    while ($i < $end && ($ops->[$i][1] == 32 || $ops->[$i][1] == 9)) {
        $i++;
    }
    if ($i > $start) {
        my $space_count = $i - $start;
        printf "batch_delete %d\n", $space_count;
        print "delay $min_ms\n";
    }

    # Count non-space chars remaining
    my $remaining = $end - $i;
    if ($remaining <= $start_chars) {
        # Short line — delete all at once
        if ($remaining > 0) {
            printf "batch_delete %d\n", $remaining;
            print "delay $min_ms\n";
        }
        return ($count, 0);
    }

    # Phase 2: Delete start_chars slowly (one at a time)
    for my $k ($i .. $i + $start_chars - 1) {
        printf "op delete %d\n", $ops->[$k][1];
        print "delay $start_ms\n";
    }
    $i += $start_chars;

    # Phase 3: Delete words with acceleration
    my $delay = $start_ms;
    while ($i < $end) {
        # Find word boundary (non-space chars until space or end)
        my $word_len = 0;
        my $j = $i;
        while ($j < $end && $ops->[$j][1] != 32 && $ops->[$j][1] != 9) {
            $word_len++;
            $j++;
        }
        if ($word_len > 0) {
            printf "batch_delete %d\n", $word_len;
            $delay = int($delay * $accel);
            $delay = $min_ms if $delay < $min_ms;
            print "delay $delay\n";
            $i += $word_len;
        }
        # Skip spaces
        if ($i < $end && ($ops->[$i][1] == 32 || $ops->[$i][1] == 9)) {
            my $space_start = $i;
            while ($i < $end && ($ops->[$i][1] == 32 || $ops->[$i][1] == 9)) {
                $i++;
            }
            my $space_count = $i - $space_start;
            printf "batch_delete %d\n", $space_count;
            print "delay $min_ms\n";
        }
    }

    return ($count, 0);
}
